### PR TITLE
inclusion of EditorConfig and ESLint

### PR DESCRIPTION
**Pull request by skarrakc**
please find here the app version with the inclusion of EditorConfig and ESLint tools.

### CODE REVIEW

**Comment by ss0201** [comment]
i think you have added all the files in node_modules directory (there are 31654 files changed). can you omit those?

**Comment by skarrakc** [comment]
do I have to keep only the 5 directories you mentioned in the issue ? ( eslint-config-airbnb eslint babel-eslint eslint-plugin-react eslint-plugin-meteor).

**Comment by ss0201** [comment]
they are in node_modules directory? if so, i think you should omit them because they are what should be installed by the one who cloned this repository, rather than what should be shared.

**Comment by skarrakc** [comment]
yes they are, so i will omit the hole node_modules directory.

**Comment by skarrakc** [comment]
I think that's okay now.

**Comment by ss0201** [comment]
LGTM

**Comment by skarrakc** [comment]
ok thanks! so, what is next things for me to focus on ?

**Comment by ss0201** [comment]
i've sent you a message on slack. please check it

**Pull request merged**
